
ARG BINARY=todo-service.bin

# Builder
FROM golang:alpine AS builder

#MAINTAINER Christoph Kappel <christoph@unexist.dev>
LABEL org.opencontainers.image.authors="christoph@unexist.dev"

ARG BINARY

WORKDIR /src/app
COPY . .
ENV GO111MODULE=on
RUN go mod download \
    && go build -o ${BINARY}

# Runner
FROM alpine

#MAINTAINER Christoph Kappel <christoph@unexist.dev>
LABEL org.opencontainers.image.authors="christoph@unexist.dev"

ARG BINARY
ARG PORT=8080

WORKDIR /root/
COPY --from=builder /src/app/${BINARY} ./

EXPOSE ${PORT}

# Store ARG in ENV in order to use it as a command - https://medium.com/@yangcar/arg-in-dockerfile-cmd-db22c2bc7b62
ENV COMMAND=./${BINARY}

CMD ${COMMAND}
