info:
  contact: {}
  version: '$Id: todo-service-gin-signoz/main.go,v 189 2024/09/11 09:12:50 unexist
    $'
paths:
  /id:
    get:
      description: Get new id
      produces:
      - application/json
      responses:
        "200":
          description: New ID
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      summary: Get new id
      tags:
      - Id
swagger: "2.0"
